#!/usr/bin/env php
<?php

require 'vendor/autoload.php';
require 'src/commands.php';

use Symfony\Component\Console\Application;

$settings = require 'src/settings.php';

$application = new Application();
$application->add(new GitHubImport($settings));
$application->run();
